x = int(input('Enter x: '))
y = int(input('Enter y: '))
print(x, y)
print('The sum of two numbers is:', x + y)
print('Division of two numbers is:', x / y)
print('Remainder of the division of two numbers is:', x % y)
print('Power of a number: x ^ y:', x ** y)
